#pragma once
/**
 * @file sam2695_midi_percussion_note.h
 */

#ifndef _SAM2695_MIDI_PERCUSSION_NOTE_H_
#define _SAM2695_MIDI_PERCUSSION_NOTE_H_

/**
 * @~Chinese
 * @brief 定义通道9音色库MIDI_BANK_0的音色常量。
 */
/**
 * @~English
 * @brief Define the note constants for the channel 9 timbre library MIDI_BANK-0.
 */
#define PERCUSSION_TIMBRE_1 0
#define PERCUSSION_TIMBRE_2 16
#define PERCUSSION_TIMBRE_3 40
#define PERCUSSION_TIMBRE_4 48
#define PERCUSSION_TIMBRE_5 127

/**
 * @~Chinese
 * @brief 定义通道9音色PERCUSSION_TIMBRE_1的音符常量。
 */
/**
 * @~English
 * @brief Define the note constants for channel 9 timbre PERCUSSION_TIMBRE_1.
 */
#define TIMBRE_1_NOTE_D_SHARP_1_STANDARD_SET 27
#define TIMBRE_1_NOTE_E_1_STANDARD_SET 28
#define TIMBRE_1_NOTE_F_1_STANDARD_SET 29
#define TIMBRE_1_NOTE_F_SHARP_1_STANDARD_SET 30
#define TIMBRE_1_NOTE_G_1_STANDARD_SET 31
#define TIMBRE_1_NOTE_G_SHARP_1_STANDARD_SET 32
#define TIMBRE_1_NOTE_A_1_STANDARD_SET 33
#define TIMBRE_1_NOTE_A_SHARP_1_STANDARD_SET 34
#define TIMBRE_1_NOTE_B_1_KICK_DRUM_2 35
#define TIMBRE_1_NOTE_C_2_KICK_DRUM_1 36
#define TIMBRE_1_NOTE_C_SHARP_2_SIDE_STICK 37
#define TIMBRE_1_NOTE_D_2_SNARE_DRUM_1 38
#define TIMBRE_1_NOTE_D_SHARP_2_HAND_CLAP 39
#define TIMBRE_1_NOTE_E_2_SNARE_DRUM_2 40
#define TIMBRE_1_NOTE_F_2_LOW_FLOOR_TOM 41
#define TIMBRE_1_NOTE_F_SHARP_2_CLOSED_HI_HAT 42
#define TIMBRE_1_NOTE_G_2_HIGH_FLOOR_TOM 43
#define TIMBRE_1_NOTE_G_SHARP_2_PEDAL_HI_HAT 44
#define TIMBRE_1_NOTE_A_2_LOW_TOM 45
#define TIMBRE_1_NOTE_A_SHARP_2_OPEN_HI_HAT 46
#define TIMBRE_1_NOTE_B_2_LOW_MIDDLE_TOM 47
#define TIMBRE_1_NOTE_C_3_HIGH_MIDDLE_TOM 48
#define TIMBRE_1_NOTE_C_SHARP_3_CRASH_CYMBAL_1 49
#define TIMBRE_1_NOTE_D_3_HIGH_TOM 50
#define TIMBRE_1_NOTE_D_SHARP_3_RIDE_CYMBAL_1 51
#define TIMBRE_1_NOTE_E_3_CHINESE_CYMBAL 52
#define TIMBRE_1_NOTE_F_3_RIDE_BELL 53
#define TIMBRE_1_NOTE_F_SHARP_3_TAMBOURINE 54
#define TIMBRE_1_NOTE_G_3_SPLASH_CYMBAL 55
#define TIMBRE_1_NOTE_G_SHARP_3_COWBELL 56
#define TIMBRE_1_NOTE_A_3_CRASH_CYMBAL_2 57
#define TIMBRE_1_NOTE_A_SHARP_3_VIBRA_SLAP 58
#define TIMBRE_1_NOTE_B_3_RIDE_CYMBAL_2 59
#define TIMBRE_1_NOTE_C_4_HIGH_BONGO 60
#define TIMBRE_1_NOTE_C_SHARP_4_LOW_BONGO 61
#define TIMBRE_1_NOTE_D_4_MUTE_HIGH_CONGA 62
#define TIMBRE_1_NOTE_D_SHARP_4_OPEN_HIGH_CONGA 63
#define TIMBRE_1_NOTE_E_4_LOW_CONGA 64
#define TIMBRE_1_NOTE_F_4_HIGH_TIMBALE 65
#define TIMBRE_1_NOTE_F_SHARP_4_LOW_TIMBALE 66
#define TIMBRE_1_NOTE_G_4_HIGH_AGOGO 67
#define TIMBRE_1_NOTE_G_SHARP_4_LOW_AGOGO 68
#define TIMBRE_1_NOTE_A_4_CABASA 69
#define TIMBRE_1_NOTE_A_SHARP_4_MARACAS 70
#define TIMBRE_1_NOTE_B_4_SHORT_WHISTLE 71
#define TIMBRE_1_NOTE_C_5_LONG_WHISTLE 72
#define TIMBRE_1_NOTE_C_SHARP_5_SHORT_GUIRO 73
#define TIMBRE_1_NOTE_D_5_LONG_GUIRO 74
#define TIMBRE_1_NOTE_D_SHARP_5_CLAVES 75
#define TIMBRE_1_NOTE_E_5_HIGH_WOOD_BLOCK 76
#define TIMBRE_1_NOTE_F_5_LOW_WOOD_BLOCK 77
#define TIMBRE_1_NOTE_F_SHARP_5_MUTE_CUICA 78
#define TIMBRE_1_NOTE_G_5_OPEN_CUICA 79
#define TIMBRE_1_NOTE_G_SHARP_5_MUTE_TRIANGLE 80
#define TIMBRE_1_NOTE_A_5_OPEN_TRIANGLE 81
#define TIMBRE_1_NOTE_A_SHARP_5_STANDARD_SET 82
#define TIMBRE_1_NOTE_B_5_STANDARD_SET 83
#define TIMBRE_1_NOTE_C_6_STANDARD_SET 84
#define TIMBRE_1_NOTE_C_SHARP_6_STANDARD_SET 85
#define TIMBRE_1_NOTE_D_6_STANDARD_SET 86
#define TIMBRE_1_NOTE_D_SHARP_6_STANDARD_SET 87
#define TIMBRE_1_NOTE_E_6_STANDARD_SET 88
#define TIMBRE_1_NOTE_F_6_STANDARD_SET 89
#define TIMBRE_1_NOTE_F_SHARP_6_STANDARD_SET 90
#define TIMBRE_1_NOTE_G_6_STANDARD_SET 91
#define TIMBRE_1_NOTE_G_SHARP_6_STANDARD_SET 92
#define TIMBRE_1_NOTE_A_6_STANDARD_SET 93
#define TIMBRE_1_NOTE_A_SHARP_6_STANDARD_SET 94
#define TIMBRE_1_NOTE_B_6_STANDARD_SET 95
#define TIMBRE_1_NOTE_C_7_STANDARD_SET 96
#define TIMBRE_1_NOTE_C_SHARP_7_STANDARD_SET 97
#define TIMBRE_1_NOTE_D_7_STANDARD_SET 98
#define TIMBRE_1_NOTE_D_SHARP_7_STANDARD_SET 99
#define TIMBRE_1_NOTE_E_7_STANDARD_SET 100
#define TIMBRE_1_NOTE_F_7_STANDARD_SET 101
#define TIMBRE_1_NOTE_F_SHARP_7_STANDARD_SET 102
#define TIMBRE_1_NOTE_G_7_STANDARD_SET 103
#define TIMBRE_1_NOTE_G_SHARP_7_STANDARD_SET 104
#define TIMBRE_1_NOTE_A_7_STANDARD_SET 105
#define TIMBRE_1_NOTE_A_SHARP_7_STANDARD_SET 106

/**
 * @~Chinese
 * @brief 定义通道9音色PERCUSSION_TIMBRE_2的音符常量。
 */
/**
 * @~English
 * @brief Define the note constants for channel 9 timbre PERCUSSION_TIMBRE_2.
 */
#define TIMBRE_2_NOTE_D_SHARP_1_STANDARD_SET 27
#define TIMBRE_2_NOTE_E_1_STANDARD_SET 28
#define TIMBRE_2_NOTE_F_1_STANDARD_SET 29
#define TIMBRE_2_NOTE_F_SHARP_1_STANDARD_SET 30
#define TIMBRE_2_NOTE_G_1_STANDARD_SET 31
#define TIMBRE_2_NOTE_G_SHARP_1_STANDARD_SET 32
#define TIMBRE_2_NOTE_A_1_STANDARD_SET 33
#define TIMBRE_2_NOTE_A_SHARP_1_STANDARD_SET 34
#define TIMBRE_2_NOTE_B_1_STANDARD_SET 35
#define TIMBRE_2_NOTE_C_2_STANDARD_SET 36
#define TIMBRE_2_NOTE_C_SHARP_2_STANDARD_SET 37
#define TIMBRE_2_NOTE_D_2_GATED_SNARE 38
#define TIMBRE_2_NOTE_D_SHARP_2_STANDARD_SET 39
#define TIMBRE_2_NOTE_E_2_STANDARD_SET 40
#define TIMBRE_2_NOTE_F_2_STANDARD_SET 41
#define TIMBRE_2_NOTE_F_SHARP_2_STANDARD_SET 42
#define TIMBRE_2_NOTE_G_2_STANDARD_SET 43
#define TIMBRE_2_NOTE_G_SHARP_2_STANDARD_SET 44
#define TIMBRE_2_NOTE_A_2_STANDARD_SET 45
#define TIMBRE_2_NOTE_A_SHARP_2_STANDARD_SET 46
#define TIMBRE_2_NOTE_B_2_GUN_SHOT 47
#define TIMBRE_2_NOTE_C_3_STANDARD_SET 48
#define TIMBRE_2_NOTE_C_SHARP_3_STANDARD_SET 49
#define TIMBRE_2_NOTE_D_3_STANDARD_SET 50
#define TIMBRE_2_NOTE_D_SHARP_3_STANDARD_SET 51
#define TIMBRE_2_NOTE_E_3_STANDARD_SET 52
#define TIMBRE_2_NOTE_F_3_STANDARD_SET 53
#define TIMBRE_2_NOTE_F_SHARP_3_STANDARD_SET 54
#define TIMBRE_2_NOTE_G_3_STANDARD_SET 55
#define TIMBRE_2_NOTE_G_SHARP_3_STANDARD_SET 56
#define TIMBRE_2_NOTE_A_3_STANDARD_SET 57
#define TIMBRE_2_NOTE_A_SHARP_3_STANDARD_SET 58
#define TIMBRE_2_NOTE_B_3_STANDARD_SET 59
#define TIMBRE_2_NOTE_C_4_STANDARD_SET 60
#define TIMBRE_2_NOTE_C_SHARP_4_STANDARD_SET 61
#define TIMBRE_2_NOTE_D_4_STANDARD_SET 62
#define TIMBRE_2_NOTE_D_SHARP_4_STANDARD_SET 63
#define TIMBRE_2_NOTE_E_4_STANDARD_SET 64
#define TIMBRE_2_NOTE_F_4_STANDARD_SET 65
#define TIMBRE_2_NOTE_F_SHARP_4_STANDARD_SET 66
#define TIMBRE_2_NOTE_G_4_STANDARD_SET 67
#define TIMBRE_2_NOTE_G_SHARP_4_STANDARD_SET 68
#define TIMBRE_2_NOTE_A_4_STANDARD_SET 69
#define TIMBRE_2_NOTE_A_SHARP_4_STANDARD_SET 70
#define TIMBRE_2_NOTE_B_4_STANDARD_SET 71
#define TIMBRE_2_NOTE_C_5_STANDARD_SET 72
#define TIMBRE_2_NOTE_C_SHARP_5_STANDARD_SET 73
#define TIMBRE_2_NOTE_D_5_STANDARD_SET 74
#define TIMBRE_2_NOTE_D_SHARP_5_STANDARD_SET 75
#define TIMBRE_2_NOTE_E_5_STANDARD_SET 76
#define TIMBRE_2_NOTE_F_5_STANDARD_SET 77
#define TIMBRE_2_NOTE_F_SHARP_5_STANDARD_SET 78
#define TIMBRE_2_NOTE_G_5_STANDARD_SET 79
#define TIMBRE_2_NOTE_G_SHARP_5_STANDARD_SET 80
#define TIMBRE_2_NOTE_A_5_STANDARD_SET 81
#define TIMBRE_2_NOTE_A_SHARP_5_STANDARD_SET 82
#define TIMBRE_2_NOTE_B_5_STANDARD_SET 83
#define TIMBRE_2_NOTE_C_6_STANDARD_SET 84
#define TIMBRE_2_NOTE_C_SHARP_6_STANDARD_SET 85
#define TIMBRE_2_NOTE_D_6_STANDARD_SET 86
#define TIMBRE_2_NOTE_D_SHARP_6_STANDARD_SET 87
#define TIMBRE_2_NOTE_E_6_STANDARD_SET 88
#define TIMBRE_2_NOTE_F_6_STANDARD_SET 89
#define TIMBRE_2_NOTE_F_SHARP_6_STANDARD_SET 90
#define TIMBRE_2_NOTE_G_6_STANDARD_SET 91
#define TIMBRE_2_NOTE_G_SHARP_6_STANDARD_SET 92
#define TIMBRE_2_NOTE_A_6_STANDARD_SET 93
#define TIMBRE_2_NOTE_A_SHARP_6_STANDARD_SET 94
#define TIMBRE_2_NOTE_B_6_STANDARD_SET 95
#define TIMBRE_2_NOTE_C_7_STANDARD_SET 96
#define TIMBRE_2_NOTE_C_SHARP_7_STANDARD_SET 97
#define TIMBRE_2_NOTE_D_7_STANDARD_SET 98
#define TIMBRE_2_NOTE_D_SHARP_7_STANDARD_SET 99
#define TIMBRE_2_NOTE_E_7_STANDARD_SET 100
#define TIMBRE_2_NOTE_F_7_STANDARD_SET 101
#define TIMBRE_2_NOTE_F_SHARP_7_STANDARD_SET 102
#define TIMBRE_2_NOTE_G_7_STANDARD_SET 103
#define TIMBRE_2_NOTE_G_SHARP_7_STANDARD_SET 104
#define TIMBRE_2_NOTE_A_7_STANDARD_SET 105
#define TIMBRE_2_NOTE_A_SHARP_7_STANDARD_SET 106

/**
 * @~Chinese
 * @brief 定义通道9音色PERCUSSION_TIMBRE_3的音符常量。
 */
/**
 * @~English
 * @brief Define the note constants for channel 9 timbre PERCUSSION_TIMBRE_3.
 */
#define TIMBRE_3_NOTE_D_SHARP_1_STANDARD_SET 27
#define TIMBRE_3_NOTE_E_1_STANDARD_SET 28
#define TIMBRE_3_NOTE_F_1_STANDARD_SET 29
#define TIMBRE_3_NOTE_F_SHARP_1_STANDARD_SET 30
#define TIMBRE_3_NOTE_G_1_STANDARD_SET 31
#define TIMBRE_3_NOTE_G_SHARP_1_STANDARD_SET 32
#define TIMBRE_3_NOTE_A_1_STANDARD_SET 33
#define TIMBRE_3_NOTE_A_SHARP_1_STANDARD_SET 34
#define TIMBRE_3_NOTE_B_1_JAZZ_BASS_DRUM_2 35
#define TIMBRE_3_NOTE_C_2_JAZZ_BASS_DRUM_1 36
#define TIMBRE_3_NOTE_C_SHARP_2_STANDARD_SET 37
#define TIMBRE_3_NOTE_D_2_BRUSH_TAP 38
#define TIMBRE_3_NOTE_D_SHARP_2_BRUSH_SLAP 39
#define TIMBRE_3_NOTE_E_2_BRUSH_SWIRL 40
#define TIMBRE_3_NOTE_F_2_STANDARD_SET 41
#define TIMBRE_3_NOTE_F_SHARP_2_STANDARD_SET 42
#define TIMBRE_3_NOTE_G_2_STANDARD_SET 43
#define TIMBRE_3_NOTE_G_SHARP_2_STANDARD_SET 44
#define TIMBRE_3_NOTE_A_2_STANDARD_SET 45
#define TIMBRE_3_NOTE_A_SHARP_2_STANDARD_SET 46
#define TIMBRE_3_NOTE_B_2_STANDARD_SET 47
#define TIMBRE_3_NOTE_C_3_STANDARD_SET 48
#define TIMBRE_3_NOTE_C_SHARP_3_STANDARD_SET 49
#define TIMBRE_3_NOTE_D_3_STANDARD_SET 50
#define TIMBRE_3_NOTE_D_SHARP_3_STANDARD_SET 51
#define TIMBRE_3_NOTE_E_3_STANDARD_SET 52
#define TIMBRE_3_NOTE_F_3_STANDARD_SET 53
#define TIMBRE_3_NOTE_F_SHARP_3_STANDARD_SET 54
#define TIMBRE_3_NOTE_G_3_STANDARD_SET 55
#define TIMBRE_3_NOTE_G_SHARP_3_STANDARD_SET 56
#define TIMBRE_3_NOTE_A_3_STANDARD_SET 57
#define TIMBRE_3_NOTE_A_SHARP_3_STANDARD_SET 58
#define TIMBRE_3_NOTE_B_3_STANDARD_SET 59
#define TIMBRE_3_NOTE_C_4_STANDARD_SET 60
#define TIMBRE_3_NOTE_C_SHARP_4_STANDARD_SET 61
#define TIMBRE_3_NOTE_D_4_STANDARD_SET 62
#define TIMBRE_3_NOTE_D_SHARP_4_STANDARD_SET 63
#define TIMBRE_3_NOTE_E_4_STANDARD_SET 64
#define TIMBRE_3_NOTE_F_4_STANDARD_SET 65
#define TIMBRE_3_NOTE_F_SHARP_4_STANDARD_SET 66
#define TIMBRE_3_NOTE_G_4_STANDARD_SET 67
#define TIMBRE_3_NOTE_G_SHARP_4_STANDARD_SET 68
#define TIMBRE_3_NOTE_A_4_STANDARD_SET 69
#define TIMBRE_3_NOTE_A_SHARP_4_STANDARD_SET 70
#define TIMBRE_3_NOTE_B_4_STANDARD_SET 71
#define TIMBRE_3_NOTE_C_5_STANDARD_SET 72
#define TIMBRE_3_NOTE_C_SHARP_5_STANDARD_SET 73
#define TIMBRE_3_NOTE_D_5_STANDARD_SET 74
#define TIMBRE_3_NOTE_D_SHARP_5_STANDARD_SET 75
#define TIMBRE_3_NOTE_E_5_STANDARD_SET 76
#define TIMBRE_3_NOTE_F_5_STANDARD_SET 77
#define TIMBRE_3_NOTE_F_SHARP_5_STANDARD_SET 78
#define TIMBRE_3_NOTE_G_5_STANDARD_SET 79
#define TIMBRE_3_NOTE_G_SHARP_5_STANDARD_SET 80
#define TIMBRE_3_NOTE_A_5_STANDARD_SET 81
#define TIMBRE_3_NOTE_A_SHARP_5_STANDARD_SET 82
#define TIMBRE_3_NOTE_B_5_STANDARD_SET 83
#define TIMBRE_3_NOTE_C_6_STANDARD_SET 84
#define TIMBRE_3_NOTE_C_SHARP_6_STANDARD_SET 85
#define TIMBRE_3_NOTE_D_6_STANDARD_SET 86
#define TIMBRE_3_NOTE_D_SHARP_6_STANDARD_SET 87
#define TIMBRE_3_NOTE_E_6_STANDARD_SET 88
#define TIMBRE_3_NOTE_F_6_STANDARD_SET 89
#define TIMBRE_3_NOTE_F_SHARP_6_STANDARD_SET 90
#define TIMBRE_3_NOTE_G_6_STANDARD_SET 91
#define TIMBRE_3_NOTE_G_SHARP_6_STANDARD_SET 92
#define TIMBRE_3_NOTE_A_6_STANDARD_SET 93
#define TIMBRE_3_NOTE_A_SHARP_6_STANDARD_SET 94
#define TIMBRE_3_NOTE_B_6_STANDARD_SET 95
#define TIMBRE_3_NOTE_C_7_STANDARD_SET 96
#define TIMBRE_3_NOTE_C_SHARP_7_STANDARD_SET 97
#define TIMBRE_3_NOTE_D_7_STANDARD_SET 98
#define TIMBRE_3_NOTE_D_SHARP_7_STANDARD_SET 99
#define TIMBRE_3_NOTE_E_7_STANDARD_SET 100
#define TIMBRE_3_NOTE_F_7_STANDARD_SET 101
#define TIMBRE_3_NOTE_F_SHARP_7_STANDARD_SET 102
#define TIMBRE_3_NOTE_G_7_STANDARD_SET 103
#define TIMBRE_3_NOTE_G_SHARP_7_STANDARD_SET 104
#define TIMBRE_3_NOTE_A_7_STANDARD_SET 105
#define TIMBRE_3_NOTE_A_SHARP_7_STANDARD_SET 106

/**
 * @~Chinese
 * @brief 定义通道9音色PERCUSSION_TIMBRE_4的音符常量。
 */
/**
 * @~English
 * @brief Define the note constants for channel 9 timbre PERCUSSION_TIMBRE_4.
 */
#define TIMBRE_4_NOTE_D_SHARP_1_CLOSED_HI_HAT 27
#define TIMBRE_4_NOTE_E_1_PEDAL_HI_HAT 28
#define TIMBRE_4_NOTE_F_1_OPEN_HI_HAT 29
#define TIMBRE_4_NOTE_F_SHARP_1_RIDE_CYMBAL 30
#define TIMBRE_4_NOTE_G_1_STANDARD_SET 31
#define TIMBRE_4_NOTE_G_SHARP_1_STANDARD_SET 32
#define TIMBRE_4_NOTE_A_1_STANDARD_SET 33
#define TIMBRE_4_NOTE_A_SHARP_1_STANDARD_SET 34
#define TIMBRE_4_NOTE_B_1_STANDARD_SET 35
#define TIMBRE_4_NOTE_C_2_GUN_SHOT 36
#define TIMBRE_4_NOTE_C_SHARP_2_STANDARD_SET 37
#define TIMBRE_4_NOTE_D_2_SNARE_DRUM_2 38
#define TIMBRE_4_NOTE_D_SHARP_2_CASTANETS 39
#define TIMBRE_4_NOTE_E_2_SNARE_DRUM_1 40
#define TIMBRE_4_NOTE_F_2_TIMPANI_1 41
#define TIMBRE_4_NOTE_F_SHARP_2_TIMPANI_2 42
#define TIMBRE_4_NOTE_G_2_TIMPANI_3 43
#define TIMBRE_4_NOTE_G_SHARP_2_TIMPANI_4 44
#define TIMBRE_4_NOTE_A_2_TIMPANI_5 45
#define TIMBRE_4_NOTE_A_SHARP_2_TIMPANI_6 46
#define TIMBRE_4_NOTE_B_2_TIMPANI_7 47
#define TIMBRE_4_NOTE_C_3_TIMPANI_8 48
#define TIMBRE_4_NOTE_C_SHARP_3_TIMPANI_9 49
#define TIMBRE_4_NOTE_D_3_TIMPANI_10 50
#define TIMBRE_4_NOTE_D_SHARP_3_TIMPANI_11 51
#define TIMBRE_4_NOTE_E_3_TIMPANI_12 52
#define TIMBRE_4_NOTE_F_3_TIMPANI_13 53
#define TIMBRE_4_NOTE_F_SHARP_3_STANDARD_SET 54
#define TIMBRE_4_NOTE_G_3_STANDARD_SET 55
#define TIMBRE_4_NOTE_G_SHARP_3_STANDARD_SET 56
#define TIMBRE_4_NOTE_A_3_STANDARD_SET 57
#define TIMBRE_4_NOTE_A_SHARP_3_STANDARD_SET 58
#define TIMBRE_4_NOTE_B_3_STANDARD_SET 59
#define TIMBRE_4_NOTE_C_4_STANDARD_SET 60
#define TIMBRE_4_NOTE_C_SHARP_4_STANDARD_SET 61
#define TIMBRE_4_NOTE_D_4_STANDARD_SET 62
#define TIMBRE_4_NOTE_D_SHARP_4_STANDARD_SET 63
#define TIMBRE_4_NOTE_E_4_STANDARD_SET 64
#define TIMBRE_4_NOTE_F_4_STANDARD_SET 65
#define TIMBRE_4_NOTE_F_SHARP_4_STANDARD_SET 66
#define TIMBRE_4_NOTE_G_4_STANDARD_SET 67
#define TIMBRE_4_NOTE_G_SHARP_4_STANDARD_SET 68
#define TIMBRE_4_NOTE_A_4_STANDARD_SET 69
#define TIMBRE_4_NOTE_A_SHARP_4_STANDARD_SET 70
#define TIMBRE_4_NOTE_B_4_STANDARD_SET 71
#define TIMBRE_4_NOTE_C_5_STANDARD_SET 72
#define TIMBRE_4_NOTE_C_SHARP_5_STANDARD_SET 73
#define TIMBRE_4_NOTE_D_5_STANDARD_SET 74
#define TIMBRE_4_NOTE_D_SHARP_5_STANDARD_SET 75
#define TIMBRE_4_NOTE_E_5_STANDARD_SET 76
#define TIMBRE_4_NOTE_F_5_STANDARD_SET 77
#define TIMBRE_4_NOTE_F_SHARP_5_STANDARD_SET 78
#define TIMBRE_4_NOTE_G_5_STANDARD_SET 79
#define TIMBRE_4_NOTE_G_SHARP_5_STANDARD_SET 80
#define TIMBRE_4_NOTE_A_5_STANDARD_SET 81
#define TIMBRE_4_NOTE_A_SHARP_5_STANDARD_SET 82
#define TIMBRE_4_NOTE_B_5_STANDARD_SET 83
#define TIMBRE_4_NOTE_C_6_STANDARD_SET 84
#define TIMBRE_4_NOTE_C_SHARP_6_STANDARD_SET 85
#define TIMBRE_4_NOTE_D_6_STANDARD_SET 86
#define TIMBRE_4_NOTE_D_SHARP_6_STANDARD_SET 87
#define TIMBRE_4_NOTE_E_6_APPLAUSES 88
#define TIMBRE_4_NOTE_F_6_STANDARD_SET 89
#define TIMBRE_4_NOTE_F_SHARP_6_STANDARD_SET 90
#define TIMBRE_4_NOTE_G_6_STANDARD_SET 91
#define TIMBRE_4_NOTE_G_SHARP_6_STANDARD_SET 92
#define TIMBRE_4_NOTE_A_6_STANDARD_SET 93
#define TIMBRE_4_NOTE_A_SHARP_6_STANDARD_SET 94
#define TIMBRE_4_NOTE_B_6_STANDARD_SET 95
#define TIMBRE_4_NOTE_C_7_STANDARD_SET 96
#define TIMBRE_4_NOTE_C_SHARP_7_STANDARD_SET 97
#define TIMBRE_4_NOTE_D_7_STANDARD_SET 98
#define TIMBRE_4_NOTE_D_SHARP_7_STANDARD_SET 99
#define TIMBRE_4_NOTE_E_7_STANDARD_SET 100
#define TIMBRE_4_NOTE_F_7_STANDARD_SET 101
#define TIMBRE_4_NOTE_F_SHARP_7_STANDARD_SET 102
#define TIMBRE_4_NOTE_G_7_STANDARD_SET 103
#define TIMBRE_4_NOTE_G_SHARP_7_STANDARD_SET 104
#define TIMBRE_4_NOTE_A_7_STANDARD_SET 105
#define TIMBRE_4_NOTE_A_SHARP_7_STANDARD_SET 106

/**
 * @~Chinese
 * @brief 定义通道9音色PERCUSSION_TIMBRE_5的音符常量。
 */
/**
 * @~English
 * @brief Define the note constants for channel 9 timbre PERCUSSION_TIMBRE_5.
 */
#define TIMBRE_5_NOTE_B_1_KICK_DRUM_1 35
#define TIMBRE_5_NOTE_C_2_KICK_DRUM_2 36
#define TIMBRE_5_NOTE_C_SHARP_2_RIM_SHOT 37
#define TIMBRE_5_NOTE_D_2_SNARE_DRUM 38
#define TIMBRE_5_NOTE_D_SHARP_2_HAND_CLAP 39
#define TIMBRE_5_NOTE_E_2_ELECTRIC_SNARE_DRUM 40
#define TIMBRE_5_NOTE_F_2_ACOUSTIC_LOW_TOM_1 41
#define TIMBRE_5_NOTE_F_SHARP_2_CLOSED_HI_HAT 42
#define TIMBRE_5_NOTE_G_2_ACOUSTIC_LOW_TOM_2 43
#define TIMBRE_5_NOTE_G_SHARP_2_OPEN_HI_HAT_2 44
#define TIMBRE_5_NOTE_A_2_ACOUSTIC_MIDDLE_TOM_1 45
#define TIMBRE_5_NOTE_A_SHARP_2_OPEN_HI_HAT_1 46
#define TIMBRE_5_NOTE_B_2_ACOUSTIC_MIDDLE_TOM_2 47
#define TIMBRE_5_NOTE_C_3_ACOUSTIC_HIGHT_TOM_1 48
#define TIMBRE_5_NOTE_C_SHARP_3_CRASH_CYMBAL 49
#define TIMBRE_5_NOTE_D_3ACOUSTIC_HIGH_TOM_2 50
#define TIMBRE_5_NOTE_D_SHARP_3_RIDE_CYMBAL 51
#define TIMBRE_5_NOTE_F_SHARP_3_TAMBOURINE 54
#define TIMBRE_5_NOTE_G_SHARP_3_COWBELL 56
#define TIMBRE_5_NOTE_C_4_STANDARD_SET 60
#define TIMBRE_5_NOTE_C_SHARP_4_STANDARD_SET 61
#define TIMBRE_5_NOTE_D_4_STANDARD_SET 62
#define TIMBRE_5_NOTE_D_SHARP_4_STANDARD_SET 63
#define TIMBRE_5_NOTE_E_4_STANDARD_SET 64
#define TIMBRE_5_NOTE_F_4_STANDARD_SET 65
#define TIMBRE_5_NOTE_F_SHARP_4_STANDARD_SET 66
#define TIMBRE_5_NOTE_G_4_STANDARD_SET 67
#define TIMBRE_5_NOTE_G_SHARP_4_STANDARD_SET 68
#define TIMBRE_5_NOTE_A_4_STANDARD_SET 69
#define TIMBRE_5_NOTE_A_SHARP_4_STANDARD_SET 70
#define TIMBRE_5_NOTE_B_4_STANDARD_SET 71
#define TIMBRE_5_NOTE_C_5_STANDARD_SET 72
#define TIMBRE_5_NOTE_C_SHARP_5_VIBRA_SLAP 73
#define TIMBRE_5_NOTE_D_SHARP_5_CLAVES 75
#define TIMBRE_5_NOTE_A_SHARP_5_APPLAUSES 82
#define TIMBRE_5_NOTE_A_SHARP_6_HELICOPTER 94
#define TIMBRE_5_NOTE_C_7_STANDARD_SET 96
#define TIMBRE_5_NOTE_F_SHARP_7_BIRDS 102
#define TIMBRE_5_NOTE_A_SHARP_7_SEASHORE 106

#endif
